### ISSUE TITLE
[BUG] Module is not usable after installation

### ISSUE THREAD

**Issue by ghost** [quonic/ProxmoxCLI#3]
**Describe the bug**
Commands are not available after installation and import of ProxmoxCLI module

**To Reproduce**
1. git clone https://github.com/quonic/ProxmoxCLI.git
2. cd .\ProxmoxCLI\
3. .\build.ps1
4. Get-Command -Module ProxmoxCLI is empty list
  4.1  Connect-PveServer is not recognized as the name of cmdlet

**Expected behavior**
Module and inside commands are available to use after installation

**Desktop (please complete the following information):**
 - OS: 2004 Build 19041.329 
 - Edition of Powershell: Desktop
 - Version: 5.1.19041.1

[output-from-build.txt](https://github.com/quonic/ProxmoxCLI/files/4846185/output-from-build.txt)

**Comment by quonic** [comment]
It imports correctly this time, but there seems to be other issues that Pester or other something else introduced. I might need to rewrite the build and test scripts for the latest version of Pester.

This still isn't production ready and should not be used.
